#include "stdafx.h"
#include "BaseParamDlg.h"

#include "../MineGE/HelperClass.h"
#include "../ArxHelper/HelperClass.h"

IMPLEMENT_DYNAMIC(BaseParamDlg, CDialog)

BaseParamDlg::BaseParamDlg(CWnd* pParent /*=NULL*/)
: CDialog(BaseParamDlg::IDD, pParent)
, m_name(_T(""))
, m_district(_T(""))
{

}

BaseParamDlg::~BaseParamDlg()
{
}

void BaseParamDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
	DDX_Text(pDX, IDC_NAME_EDIT, m_name);
	DDX_Text(pDX, IDC_DISTRICT_EDIT, m_district);
	DDX_Control(pDX, IDC_METHODS_COMBO, m_method);
	DDX_Control(pDX, IDC_WAYS_COMBO, m_way);
}


BEGIN_MESSAGE_MAP(BaseParamDlg, CDialog)
	ON_BN_CLICKED( IDOK, &BaseParamDlg::OnBnClickedOk )
END_MESSAGE_MAP()

void BaseParamDlg::readPropertyData()
{
	AcDbObjectId objId;
	SingleDataObjectHelper::GetObjectId( _T( "基本参数" ), objId );

	DataHelper::GetPropertyData( objId, _T( "矿井名" ), m_name );
	DataHelper::GetPropertyData( objId, _T( "所属采区" ), m_district );


	m_method.AddString( _T( "压入式" ) );
	m_method.AddString( _T( "抽出式" ) );
	CString v1;
	DataHelper::GetPropertyData( objId, _T( "通风方法" ), v1 );
	int vt = 0;
	ArxUtilHelper::StringToInt( v1, vt );
	vt = vt % 2; // 范围：{0, 1}
	m_method.SetCurSel( vt );

	m_way.AddString( _T( "辅助风筒" ) );
	m_way.AddString( _T( "间断风筒" ) );
	m_way.AddString( _T( "单机双列" ) );
	m_way.AddString( _T( "串联局扇" ) );
	m_way.AddString( _T( "混合通风" ) );
	m_way.AddString( _T( "风柜通风" ) );
	m_way.AddString( _T( "风库通风" ) );
	m_way.AddString( _T( "钻孔通风" ) );
	CString v2;
	DataHelper::GetPropertyData( objId, _T( "通风方式" ), v2 );

	int vw = 0;
	ArxUtilHelper::StringToInt( v2, vw );
	vw = vw % 8; // 范围：{0, 1，2，3，4，5，6，7}
	m_way.SetCurSel( vw );
	UpdateData( FALSE );
}

void BaseParamDlg::writePropertyData()
{
	UpdateData( TRUE );

	AcDbObjectId objId;
	SingleDataObjectHelper::GetObjectId( _T( "基本参数" ), objId );

	DataHelper::SetPropertyData( objId, _T( "矿井名" ), m_name );
	DataHelper::SetPropertyData( objId, _T( "所属采区" ), m_district );

	CString v1;
	v1.Format( _T( "%d" ), m_method.GetCurSel() );
	DataHelper::SetPropertyData( objId, _T( "通风方法" ), v1 );

	CString v2;
	v2.Format( _T( "%d" ), m_way.GetCurSel() );
	DataHelper::SetPropertyData( objId, _T( "通风方式" ), v2 );

}

BOOL BaseParamDlg::OnInitDialog()
{
	CDialog::OnInitDialog();

	readPropertyData();

	return TRUE;  // return TRUE unless you set the focus to a control
	// 异常: OCX 属性页应返回 FALSE

}

void BaseParamDlg::OnBnClickedOk()
{
	writePropertyData();
	OnOK();
}
